# Generated by Django 5.2.1 on 2025-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventregistration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
