# Generated by Django 5.2.1 on 2025-05-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='VendorBooking',
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
